[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:streamlit]
command=streamlit run /app/main.py --server.port=8501 --server.address=127.0.0.1
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:jupyter]
command=jupyter lab --ip=127.0.0.1 --port=8889 --no-browser --allow-root --notebook-dir=/app/notebooks --ServerApp.token= --ServerApp.password= --ServerApp.base_url=%(ENV_NB_PREFIX)s/jupyter/ --ServerApp.allow_origin=* --ServerApp.disable_check_xsrf=True --ServerApp.allow_remote_access=True
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/jupyter.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0
